name: Uptime Check

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Uptime Action
        uses: srt32/uptime@v0.2.1
        with:
          url-to-hit: 'https://siliconecb.cc'  # Replace with your URL
          expected-statuses: '200,301'  # Optional, default is 200
